# Generated by Django 4.1 on 2022-08-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bottom_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('symbol', models.CharField(max_length=10)),
                ('current_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
