# Generated by Django 4.1 on 2022-08-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pipeline_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='current_value',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
