# Generated by Django 4.0.7 on 2022-08-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_pipeline_current_value_pipeline_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='current_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
